name: Build iKoolProxy for OpenWrt 6.12

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/upload-artifact@v4.6.0
    # actions/checkout@main
    

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.2  # Compatible with kernel 6.12

    - name: Update Feed
      working-directory: openwrt
      run: |
        echo "src-git koolproxy https://github.com/ilxp/luci-app-ikoolproxy.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure Build
      working-directory: openwrt
      run: |
        cat >> .config <<EOF
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        CONFIG_KERNEL_VERSION="6.12"
        CONFIG_PACKAGE_luci-app-ikoolproxy=y
        CONFIG_PACKAGE_iptables-mod-nat-extra=y
        CONFIG_PACKAGE_kmod-ipt-extra=y
        CONFIG_PACKAGE_diffutils=y
        CONFIG_PACKAGE_openssl-util=y
        CONFIG_PACKAGE_dnsmasq-full=y
        CONFIG_PACKAGE_ca-bundle=y
        CONFIG_PACKAGE_ca-certificates=y
        CONFIG_PACKAGE_libustream-openssl=y
        CONFIG_PACKAGE_lua-openssl=y
        EOF
        make defconfig

    - name: Download Package Sources
      working-directory: openwrt
      run: make download -j8

    - name: Build Package
      working-directory: openwrt
      run: |
        make package/luci-app-ikoolproxy/compile V=s -j$(nproc)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ikoolproxy-packages
        path: openwrt/bin/packages/*/koolproxy/luci-app-ikoolproxy*.ipk
        
